services:
  inventory:
    base-url: ${INVENTORY_SERVICE_URL:${MS_INVENTARIO_URL:http://host.docker.internal:8081}}
  sales:
    base-url: ${SALES_SERVICE_URL:${MS_VENTAS_URL:http://host.docker.internal:8082}}
  purchases:
    base-url: ${PURCHASES_SERVICE_URL:${MS_COMPRAS_URL:http://host.docker.internal:8083}}
