agrocenter:
  security:
    jwt:
      issuer-uri: ${COGNITO_ISSUER_URI}
      jwk-set-uri: ${COGNITO_JWK_SET_URI}
      audience: ${COGNITO_AUDIENCE}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:https://front-web-seven.vercel.app,http://localhost:3000,http://localhost:5173}
    allowed-origin-patterns: ${ALLOWED_ORIGIN_PATTERNS:https://*.vercel.app}

services:
  inventory:
    base-url: ${MS_INVENTARIO_URL}
  sales:
    base-url: ${MS_VENTAS_URL}
  purchases:
    base-url: ${MS_COMPRAS_URL}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
